# Generated by Django 3.0.6 on 2020-05-16 05:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datalabel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='author',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestmodel',
            name='categories',
            field=models.TextField(default=django.utils.timezone.now, help_text='please provide in                                              [cat1, cat2, cat3] format'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='dateCreated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='projectDesc',
            field=models.TextField(),
        ),
    ]
