# Generated by Django 3.0.6 on 2020-05-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalabel', '0002_auto_20200516_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='ready',
            field=models.CharField(default='not ready', max_length=10),
        ),
    ]
