# Generated by Django 3.0.6 on 2020-05-17 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalabel', '0003_requestmodel_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='categories',
            field=models.TextField(help_text='please provide in                                              cat1, cat2, cat3 format'),
        ),
    ]
